### PR TITLE
feat: sql database set up

### PR DESCRIPTION
**Pull request by teran-joseluis**
## Related Tickets & US
- [Set up DB configuration](https://app.clickup.com/t/868avv753)

## Description

This PR is on charge of configuring different environments such as **dev**, **stage** and **prod** having each one its `.yaml` file configuration.

Before running docker, you should run the next command to have the `.jar` project:
```
./gradlew bootJar
```

Let's build our project image
```
docker build -t argos-api-app-dev -f Dockerfile.dev .
```

Just run our container to have the database into postgresql
```
docker compose -f docker-compose-dev.yml up argos_api_app_dev
```

Finally, enter to postgresql and to our database also using the next command:
```
docker exec -it argos_api_postgres_dev psql -U user -d argos_api_dev_db
```

Once you're in, you can follow the next commands to see the tables and flyway schema history:
```
\dt
```

Something like this:
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Build configuration change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26)

### CODE REVIEW

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Good job. I've left some requests regarding the port the API is running on.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26#-:-OCu-rsGDkdWTNez3bIg:b7oqczd)* status: all files reviewed, 2 unresolved discussions (waiting on @gabygabylagaby, @salet-gutierrez-jalafund, and @teran-joseluis)

___
*[`src/main/resources/application.yaml` line 10 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26#-OCu-OwD9D8cjJ8kUJhr:-OCu-OwD9D8cjJ8kUJhs:b-26dj9g) ([raw file](https://github.com/SoftDevSix/ArgosAPI/blob/470a8c63917fe00cc56324c3b9c926ff5d9facca/src/main/resources/application.yaml#L10)):*
> ```YAML
>     exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
> server:
>   port: 8080
> ```

ArgosAPI should run in port 8081



_Code quote:_
```YAML
server:
  port: 8080
```
___
*[`src/main/resources/application.yaml` line 13 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26#-OCu-T6u8RovSUpPFBtt:-OCu-T6u8RovSUpPFBtu:b-f4gdyn) ([raw file](https://github.com/SoftDevSix/ArgosAPI/blob/ccbd4029330e1ebabbed3f36db754315cea34fbb/src/main/resources/application.yaml#L13)):*
> ```YAML
> file:
>   manager:
>     base-url: http://localhost:8081/fileManager
> ```

FileManager is running on port 8080

**Review by zrock-dev — APPROVED** [review]
:lgtm:

Please make sure the domain entities and the tables defined in the V1_INIT_TABLE.sql are the same.

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26#-:-OCu2W234v53DfjBMHpa:b-es2r1s)* status: all files reviewed, 2 unresolved discussions (waiting on @gabygabylagaby, @sebastian-barra-jalafund, and @teran-joseluis)

**Review by GabyGV-GGV — APPROVED** [review]
Good job!

**Review by sebastian-barra-jalafund — APPROVED** [review]
well done.

**Comment by teran-joseluis** [comment]
> :lgtm:
> 
> Please make sure the domain entities and the tables defined in the V1_INIT_TABLE.sql are the same.
> 
> > Reviewed 9 of 9 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/26#-:-OCu2W234v53DfjBMHpa:b-es2r1s)_ status: all files reviewed, 2 unresolved discussions (waiting on @gabygabylagaby, @sebastian-barra-jalafund, and @teran-joseluis)

Yeah, you're right but I suggest to merge this PR due to those changes. Since my ticket had been opened for a long time it'd be better to merge it please. I can do it into another PR during the development with our teammates.

**Comment by teran-joseluis** [comment]
@zrock-dev @gabygabylagaby @sebastian-barra-jalafund 

Hi team,
Can any of you merge this PR please?

**Pull request merged**
