### PR TITLE
feat: refactor get endpoints

### PR DESCRIPTION
**Pull request by leonardo-herrera-jalafund**
## Related Tickets & US
- [[CS-56-03]](https://app.clickup.com/t/868b3x04z)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

You can test the implementation following this steps:
- Run the FileManager API
- Execute the POST endpoint of notification with the project ID
- Execute the POST endpoint of the rules with the project ID and params
- Execute the GET endpoint of the project coverage with tjhe project ID

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37)

### CODE REVIEW

**Comment by zrock-dev** [comment]
Branch feature/cs-56/post-endpoint-to-rules was deleted so that it would be branched of fix/cs-43-13/get-path-FileManagerApi-coverage-report because it has fixed the /coverage/create-notification/projectCreationNotification 500 error.

I'm opening this PR again.

**Comment by zrock-dev** [comment]
I've executed a happy path test of the implementation and everything works fine. Good job!!!

In our [wiki](https://github.com/SoftDevSix/ArgosApplication/wiki/Endpoints#response), we've documented the following response:
```
{
    "projectStatus": "PASSED",
    "coverage": {
        "actualCoverage": 80.56,
        "requiredCoverage": 80.56
    },
    "rating": {
        "actualRating": "B",
        "requiredCodeRating": "B"
    }
}
```

but the actual response has more data:
```
{
  "id": null,
  "projectId": null,
  "status": "PASSED",
  "coverageResult": {
    "id": null,
    "requiredCoverage": 0,
    "totalCoverage": 65.98215
  },
  "codeAnalysisResult": {
    "id": null,
    "expectedRating": "A",
    "actualRating": "A"
  }
}
```

I think it's best to match the documented response body, this way we can avoid future integration problems.

**Review by salet-gutierrez-jalafund — CHANGES_REQUESTED** [review]
Why is null coming out in the projectId? It would be good if you get the project id since that is what we are passing as a parameter.

Screenshot from 2024-12-03 22-38-07

**Review by salet-gutierrez-jalafund — CHANGES_REQUESTED** [review]
Please document your pull request and link to the resolved issue.

image

**Review by zrock-dev — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37)* status: all files reviewed, 5 unresolved discussions (waiting on @gabygabylagaby and @leonardo-herrera-jalafund)

___
*[`src/main/java/com/softdevsix/application/services/Rules/RulesService.java` line 17 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37#-ODEXKAd9Zh0fRCTftce:-ODEXKAe0ljSSVnOp5yz:b-5xsll3) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/86b160be87e083a1003b78568bbbabebfc97cacb/src/main/java/com/softdevsix/application/services/Rules/RulesService.java#L17)):*
> ```Java
> public class RulesService implements IRulesService {
>     private final IProjectService PROJECT_SERVICE;
>     private final IFileService FILE_SERVICE;
> ```

Minor

Since PROJECT_SERVICE and  FILE_SERVICE are class attributes, what about changing their names to follow naming conventions filesErvice and projectService



_Code quote:_
```Java
    private final IProjectService PROJECT_SERVICE;
    private final IFileService FILE_SERVICE;
```
___
*[`src/main/java/com/softdevsix/application/services/Rules/RulesService.java` line 60 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37#-ODEYMF57142SYf7H-wB:-ODEYMF57142SYf7H-wC:blmttql) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/86b160be87e083a1003b78568bbbabebfc97cacb/src/main/java/com/softdevsix/application/services/Rules/RulesService.java#L60)):*
> ```Java
>         }
> 
>         PROJECT_SERVICE.calculateProjectStatus(projectId);
> ```

Major

This logic is not related with RulesService because it's using ProjectService's methods for the overall calculation. I suggest a refactor to move this logic to an appropriate place, this way we can make this class more cohesive.



_Code quote:_
```Java
        calculateFilesCoverage(project);

        if(paramsRequestDTO.isProjectCoverage()) {
            PROJECT_SERVICE.calculateProjectCoverage(projectId);
        }
        if(paramsRequestDTO.isProjectCoverage()) {
            PROJECT_SERVICE.calculateProjectRating(projectId);
        }

        PROJECT_SERVICE.calculateProjectStatus(projectId);
```
___
*[`src/main/java/com/softdevsix/presentation/controllers/ProjectMetricsController.java` line 32 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37#-ODEZr9h1vyzGwVa3rQX:-ODEZr9iC56B5PDMjKJl:byywusy) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/86b160be87e083a1003b78568bbbabebfc97cacb/src/main/java/com/softdevsix/presentation/controllers/ProjectMetricsController.java#L32)):*
> ```Java
>             return new ResponseEntity<>(HttpStatus.NOT_FOUND);
>         } catch (Exception e) {
>             return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
> ```

Minor
Would it be possible to add a message to the error. This way the user can have more information to troubleshoot the error.
___
*[`src/main/java/com/softdevsix/domain/repositories/project/ProjectRepository.java` line 19 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37#-ODEZFnn-luiPRln0pAh:-ODEZFnn-luiPRln0pAi:b-ly4utc) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/86b160be87e083a1003b78568bbbabebfc97cacb/src/main/java/com/softdevsix/domain/repositories/project/ProjectRepository.java#L19)):*
> ```Java
>     }
> 
>     private void initializeDatabase() {
> ```

Minor

Remove this empty method please
___
*[`src/main/java/com/softdevsix/domain/repositories/rules/RulesMemoryRepository.java` line 18 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/37#-ODEZRLKC5VbO1WMbQN-:-ODEZRLKC5VbO1WMbQN0:bagy6wc) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/86b160be87e083a1003b78568bbbabebfc97cacb/src/main/java/com/softdevsix/domain/repositories/rules/RulesMemoryRepository.java#L18)):*
> ```Java
>     }
> 
>     private void initializeData() {
> ```

Minor 
Remove this initializeData method. It was implemented to have hardcoded values because other modules were not implemented yet, but they have been implemented and the method is not longer required.

**Review by salet-gutierrez-jalafund — CHANGES_REQUESTED** [review]
I put this data in the rules, which in my `requiredCoveragePercentage` I put it as 80:

Screenshot from 2024-12-03 22-50-45

But when getting the coverage of the project the `requiredCoverage` is as 50, which I put that data previously for testing, does this mean that the data will not be updated even if I am making another POST?

Screenshot from 2024-12-03 22-50-27

**Comment by leonardo-herrera-jalafund** [comment]
> I've executed a happy path test of the implementation and everything works fine. Good job!!!
> 
> In our [wiki](https://github.com/SoftDevSix/ArgosApplication/wiki/Endpoints#response), we've documented the following response:
> 
> ```
> {
>     "projectStatus": "PASSED",
>     "coverage": {
>         "actualCoverage": 80.56,
>         "requiredCoverage": 80.56
>     },
>     "rating": {
>         "actualRating": "B",
>         "requiredCodeRating": "B"
>     }
> }
> ```
> 
> but the actual response has more data:
> 
> ```
> {
>   "id": null,
>   "projectId": null,
>   "status": "PASSED",
>   "coverageResult": {
>     "id": null,
>     "requiredCoverage": 0,
>     "totalCoverage": 65.98215
>   },
>   "codeAnalysisResult": {
>     "id": null,
>     "expectedRating": "A",
>     "actualRating": "A"
>   }
> }
> ```
> 
> I think it's best to match the documented response body, this way we can avoid future integration problems.

Done

**Comment by leonardo-herrera-jalafund** [comment]
> Why is null coming out in the projectId? It would be good if you get the project id since that is what we are passing as a parameter.
> 
> Screenshot from 2024-12-03 22-38-07

Done

**Comment by leonardo-herrera-jalafund** [comment]
> Please document your pull request and link to the resolved issue.
> 
> image

Done

**Comment by leonardo-herrera-jalafund** [comment]
@zrock-dev about the comments:

> This logic is not related with RulesService because it's using ProjectService's methods for the overall calculation. I suggest a refactor to move this logic to an appropriate place, this way we can make this class more cohesive.

I agree that it should go somewhere else, but due to time issues it is not feasible to do that refactor.

> Would it be possible to add a message to the error. This way the user can have more information to troubleshoot the error.

To implement that I need to change the return type of the method or make a custom response, which would change the response of the documentation, I don't know if there is an easier way.

the rest I already solved it

**Comment by zrock-dev** [comment]
Okay, given that this PR is important, I'll expect a PR with these changes implemented.

**Comment by zrock-dev** [comment]
I did a happy test of the implementation and everything looks good.

image

**Review by zrock-dev — APPROVED** [review]
LGTM

**Comment by zrock-dev** [comment]
I've discovered a bug:

image
The reported coverage is 0% even tho there is a file with coverage of more than 63% so the project coverage should be more than zero
image

**Review by GabyGV-GGV — APPROVED** [review]
Good job!

**Comment by zrock-dev** [comment]
So we have two approvals for this PR and I'll proceed with the merge.

**Pull request merged**
