### PR TITLE
feat: post endpoint to rules

### PR DESCRIPTION
**Pull request by leonardo-herrera-jalafund**
## Related Tickets & US
- [CS - 56 [SP-5] : Define rules Post endpoints](https://app.clickup.com/t/868b3tb7a)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40)

### CODE REVIEW

**Comment by zrock-dev** [comment]
fixes #31

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Good job. 

I performed a smoke testing and happy path test of the implementation and everything is working fine.

I've left some suggestions.

> Reviewed 20 of 40 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-:-ODO-otPA8qceSh4J5Ew:b8z2rt8)* status: 42 of 43 files reviewed, 10 unresolved discussions (waiting on @leonardo-herrera-jalafund, @ronaldo-mendoza-jalafund, @salet-gutierrez-jalafund, and @zamoranoalicia)

___
*[`src/main/java/com/softdevsix/domain/repositories/project/ProjectRepository.java` line 50 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNwy7z4L2SccL-Bh_d:-ODNwy7z4L2SccL-Bh_e:bgcdrdj) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/domain/repositories/project/ProjectRepository.java#L50)):*
> ```Java
>     public boolean deleteFile(UUID projectId) {
>         return projects.remove(projectId) != null;
>     }
> ```

Major

I believe this two methods are not used anywhere. What about deleting this unused code?



_Code quote:_
```Java
    public List<Project> getAll(){
        return projects.values().stream().toList();
    }

    @Override
    public boolean deleteFile(UUID projectId) {
        return projects.remove(projectId) != null;
    }
```
___
*[`src/main/java/com/softdevsix/domain/entities/project/Project.java` line 16 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNwWJ41eB3sZeq77t7:-ODNwWJ41eB3sZeq77t8:b-grhfld) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/c20b44e6b8957bc1abb43067afeaaa83a121df31/src/main/java/com/softdevsix/domain/entities/project/Project.java#L16)):*
> ```Java
> @Builder
> public class Project {
>     @GeneratedValue(strategy = GenerationType.UUID)
> ```

Please keep this annotation. It's being used in the database implementation.
___
*[`src/main/java/com/softdevsix/domain/repositories/rules/RulesMemoryRepository.java` line 15 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNz2EI41plVPPpXGjw:-ODNz2EI41plVPPpXGjx:bi0s0ae) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/domain/repositories/rules/RulesMemoryRepository.java#L15)):*
> ```Java
>     public RulesMemoryRepository() {
>         this.projectRules = new HashMap<>();
>         initializeData();
> ```

Major

Please remove hardcoded data.
___
*[`src/main/java/com/softdevsix/application/services/rules/RulesService.java` line 17 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNvedC9WFcl_Nf9xLm:-ODNvedC9WFcl_Nf9xLn:b-am0kz0) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/application/services/rules/RulesService.java#L17)):*
> ```Java
> public class RulesService implements IRulesService {
>     private final IProjectService projectService;
>     private final IFileService fileService;
> ```

Major

RulesService is the service layer, and the only interactions it has with ProjectService and FileService is to either store or update data. Would it be possible for RuleService to directly access the repositories? This way we will reduce coupling between those services.



_Code quote:_
```Java
    private final IProjectService projectService;
    private final IFileService fileService;
```
___
*[`src/main/java/com/softdevsix/application/services/project/IProjectService.java` line 0 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNueaw2E8VH11ly3OI:-ODNueaw2E8VH11ly3OJ:b-p43re8) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/application/services/project/IProjectService.java#L0)):*
Minor

Why has this file been moved?
___
*[`src/main/java/com/softdevsix/presentation/controllers/ProjectMetricsController.java` line 44 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNzIgGBlgRIEXNFvEL:-ODNzIgHEdXqyBvZULZ2:bnm8wir) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/presentation/controllers/ProjectMetricsController.java#L44)):*
> ```Java
>             return new ResponseEntity<>(resultDTO, HttpStatus.OK);
>         } catch (ProjectNotFoundException e) {
>             return new ResponseEntity<>(HttpStatus.NOT_FOUND);
> ```

minor

What about adding a explanatory message in the exception? Without this change the user only gets a "Error: response status is 404" and if we add a message it would be easier to understand what the problem is about
___
*[`src/main/java/com/softdevsix/domain/repositories/project/IProjectRepository.java` line 0 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNwpDqB5vfs-neVaig:-ODNwpDrCgpRHOVyb-I9:bvr4b0) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/domain/repositories/project/IProjectRepository.java#L0)):*
Major

Why this file has been moved?
___
*[`src/main/java/com/softdevsix/application/services/rules/IRulesService.java` line 11 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNuwVT9SP1cVLkU7Sg:-ODNuwVT9SP1cVLkU7Sh:bbwndpp) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/application/services/rules/IRulesService.java#L11)):*
> ```Java
> public interface IRulesService {
>     void saveRules(ProjectParams projectParams, UUID projectId);
>     Project executeProject(UUID projectId, ProjectParamsRequestDTO paramsRequestDTO);
> ```

Major

The responsibilty of RulesService would be rules related logic of this method `executeProject`is not related with ReportService. To make this class more cohesive, please move this method to an external class.
___
*[`src/main/java/com/softdevsix/domain/repositories/file/FileMemoryRepository.java` line 0 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNwhdV0o42CJGDAV4n:-ODNwhdV0o42CJGDAV4o:bvr4b0) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/domain/repositories/file/FileMemoryRepository.java#L0)):*
Major

Why this file has been moved?
___
*[`src/main/java/com/softdevsix/application/services/file/FileService.java` line 0 at r2](https://reviewable.io/reviews/SoftDevSix/ArgosApplication/40#-ODNuRPgBc0Nx61d9Fi9:-ODNuRPgBc0Nx61d9FiA:bl6fak) ([raw file](https://github.com/SoftDevSix/ArgosApplication/blob/6766659187d77fe2704bf7d9b16da42b8d4e982c/src/main/java/com/softdevsix/application/services/file/FileService.java#L0)):*
major

Why has this file been moved?

**Comment by leonardo-herrera-jalafund** [comment]
@zrock-dev about the comments

> I believe this two methods are not used anywhere. What about deleting this unused code?

>     public List<Project> getAll(){
>         return projects.values().stream().toList();
>     }

The method was deleted as it was no longer in use.

> @Override
>     public boolean deleteFile(UUID projectId) {
>         return projects.remove(projectId) != null;
>     }

The method was not deleted as it is used in the tests.

> @Builder
> public class Project {
>     @GeneratedValue(strategy = GenerationType.UUID)

The annotation was added back

> Why this file has been moved?

Several of the classes were not moved it was the name of the package that changed to follow naming conventions

> RulesService is the service layer, and the only interactions it has with ProjectService and FileService is to either store or update data. Would it be possible for RuleService to directly access the repositories? This way we will reduce coupling between those services.

> The responsibilty of RulesService would be rules related logic of this method executeProjectis not related with ReportService. To make this class more cohesive, please move this method to an external class.

Refactoring this part can be costly, I don't see it convenient at this stage of the project. It is not feasible to inject the repositories instead of the services because they contain logic that does not exist in the repositories.

**Comment by zrock-dev** [comment]
Okay, then I would expect a follow up PR addressing the other issues.

**Comment by zrock-dev** [comment]
> Several of the classes were not moved it was the name of the package that changed to follow naming conventions

The following command output is a list of files that have changed location from one folder to another
```
$ git diff --name-status --diff-filter=R origin/develop origin/feature/cs-56/post-endpoint-to-rules

R093    src/main/java/com/softdevsix/application/services/FileService.java      src/main/java/com/softdevsix/application/services/file/FileService.java
R086    src/main/java/com/softdevsix/application/services/IFileService.java     src/main/java/com/softdevsix/application/services/file/IFileService.java
R071    src/main/java/com/softdevsix/application/services/IProjectService.java  src/main/java/com/softdevsix/application/services/project/IProjectService.java
R095    src/main/java/com/softdevsix/domain/repositories/FileMemoryRepository.java      src/main/java/com/softdevsix/domain/repositories/file/FileMemoryRepository.java
R087    src/main/java/com/softdevsix/domain/repositories/IFileRepository.java   src/main/java/com/softdevsix/domain/repositories/file/IFileRepository.java
R052    src/main/java/com/softdevsix/domain/repositories/IProjectRepository.java        src/main/java/com/softdevsix/domain/repositories/project/IProjectRepository.java
```

Based on that data, my question remains the same. I would like to understand the reason to move those files.

**Review by ronaldo-mendoza-jalafund — APPROVED** [review]
There are some classes or methods that would be good to refactor to make the code understandable but due to lack of time this PR is approved because it meets the acceptance criteria. 
Nice Job

**Review by zrock-dev — APPROVED** [review]
So we really need this PR because of the demo deadline. My observations are about the code but the feature works as intented so I'll proceed with the merge @leonardo-herrera-jalafund please address those suggestions in a new PR

**Pull request merged**
