### PR TITLE
feat: project coverage

### PR DESCRIPTION
**Pull request by leonardo-herrera-jalafund**
Implementation of the project coverage.

## Related Tickets & US
- [[CS-43-08] Project Coverage](https://app.clickup.com/t/868b2fgmr)

## Description
Logic to get the project metrics result, including coverage percentage, rating and status.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Executng the corresponding tests
- Using the endopoint GET `/metrics/{projectId}`

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/19)

### CODE REVIEW

**Review by GabyGV-GGV — APPROVED** [review]
Good job!

**Review by zrock-dev — CHANGES_REQUESTED** [review]
I've run the project, and it is listening on port 8080 which  is good. I would like to have the swagger address to verify everything is working fine.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/19#-:-OCppWJO85U-XsAp2Jf7:b-qk605d)* status: all files reviewed, 1 unresolved discussion (waiting on @leonardo-herrera-jalafund, @sebastian-barra-jalafund, and @zamoranoalicia)

___
*[`src/main/java/com/softdevsix/api/controllers/ProjectMetricsController.java` line 15 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/19#-OCpnZmg3bXuGwVdgTan:-OCpnZmg3bXuGwVdgTao:b1e0d2w) ([raw file](https://github.com/SoftDevSix/ArgosAPI/blob/e7f5a2e5ff5d3778b83a303c6c9235e7f4e2df96/src/main/java/com/softdevsix/api/controllers/ProjectMetricsController.java#L15)):*
> ```Java
> 
> @RestController
> @RequestMapping("/metrics")
> ```

Major.

Please update the mapping to comply with the documentation (GET /coverage/project/{projectId}) This will allow the UI to use our endpoint.

**Comment by leonardo-herrera-jalafund** [comment]
@zrock-dev you can paste this link in your browser to see the endpoint in swagger: [swagger ui](http://localhost:8080/swagger-ui/index.html#). Make sure that the api is running.

**Review by zrock-dev — APPROVED** [review]
Good job
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/19#-:-OCpzBc49GTLvZZKa1xG:b1aypz3)* status: all files reviewed, 1 unresolved discussion (waiting on @leonardo-herrera-jalafund, @sebastian-barra-jalafund, and @zamoranoalicia)

**Comment by zrock-dev** [comment]
Given that this PR has 2 approves and following the communicate "Acerca de los PR",  I'll merge this PR

**Pull request merged**
