### PR TITLE
chore: set sql database configuration for different environments

### PR DESCRIPTION
**Pull request by teran-joseluis**
## Related Tickets & US
- [Set up DB configuration](https://app.clickup.com/t/868avv753)

## Description

This PR is on charge of configuring different environments such as **dev**, **stage** and **prod** having each one its `.yaml` file configuration.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Build configuration change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/3)

### CODE REVIEW

**Comment by GabyGV-GGV** [comment]
@teran-joseluis 
we need in .env so that minimally we can access to the database, and that the .github can recognize it and thus avoiding problems in the build.

**Comment by GabyGV-GGV** [comment]
Please resolve your conflicts, there is a merge conflict in:
src/main/resources/application.yaml

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Good job. I've left some suggestions.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softdevsix/argosapi/3#-:-OCkF6Ny2o9Q973h7W3s:bfqitv8)* status: all files reviewed, 2 unresolved discussions (waiting on @axel-ayala-jalafund, @teran-joseluis, and @zamoranoalicia)

___
*[`docker-compose.yml` line 0 at r1](https://reviewable.io/reviews/softdevsix/argosapi/3#-OCkEdAz3yASC471gFeo:-OCkEdAz3yASC471gFep:b5qjj8o) ([raw file](https://github.com/softdevsix/argosapi/blob/0224f6c9b20c0ccd63f0bb79a9d45eb001f96226/docker-compose.yml#L0)):*
It seems that there are spring YAML configurations for prod and stage, but this composes file is using only dev. What about adding the compose files too?
___
*[`.dockerignore` line 0 at r1](https://reviewable.io/reviews/softdevsix/argosapi/3#-OCkDwJs0qlDnFVjX9I0:-OCkDwJs0qlDnFVjX9I1:b9fwg1b) ([raw file](https://github.com/softdevsix/argosapi/blob/0224f6c9b20c0ccd63f0bb79a9d45eb001f96226/.dockerignore#L0)):*
Good job, this `dockerignore` seems complete. Would it be ok to replicate it at https://github.com/SoftDevSix/Argos/pull/11

**Review by zrock-dev — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softdevsix/argosapi/3#-:-OCpFx8g-2mV_mIALYmp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @gabygabylagaby, @leonardo-herrera-jalafund, @ronaldo-mendoza-jalafund, @salet-gutierrez-jalafund, @teran-joseluis, and @zamoranoalicia)

**Review by salet-gutierrez-jalafund — APPROVED** [review]

**Review by GabyGV-GGV — APPROVED** [review]

**Comment by zrock-dev** [comment]
I've found an error

```
1.  docker compose -f docker-compose.yml --profile development up -d
2. docker compose -f docker-compose.yml --profile development up argos_dev
```
image

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Please keep the old project structure.

**Comment by teran-joseluis** [comment]
> Please keep the old project structure.

Done.

Also, I'm just adding missing extra lines in those files which required.

**Comment by teran-joseluis** [comment]
@zamoranoalicia @zrock-dev @gabygabylagaby @salet-gutierrez-jalafund 
I’m closing this pull request because it contains a large number of commits that were inherited from another branch. Since it is now pointing to the `develop` branch, I’ll create a new [PR-26](https://github.com/SoftDevSix/ArgosAPI/pull/26) with only the relevant changes shortly.

**Pull request closed without merging**
