### PR TITLE
refactor: enhance project structure using layers

### PR DESCRIPTION
**Pull request by teran-joseluis**
## Related Tickets & US
- [Refactor Argos API Layers](https://app.clickup.com/t/868b036kx)

## Description

This **PR** sets up the necessary configuration for **Swagger** documentation while implementing a Clean Architecture based **project structure**, as outlined in my ticket. Although some teammates have already set up the Swagger configuration, they used a layered architecture approach. In contrast, this PR aligns with the Clean Architecture framework we discussed in our sessions with @zamoranoalicia .

In addition, the current **development** branch contains an inconsistent folder structure, with some additional directories that do not adhere to our intended design. This PR looks to improve the overall organization of the project by refining the folder structure and ensuring a clear and maintainable architecture.

Finally, I have changed some file names because they were written on a plural sense instead of being in a singular format. Also, as the most of our unit test files were on singular that's why I decided either to change them to singular.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Build configuration

## How Has This Been Tested?

Running the following commands:
```
./gradlew test
```
```
./gradlew build
```
```
./gradlew run
```
You should see Swagger running on port 8081, via this url http://localhost:8081/swagger-ui/index.html#/

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27)

### CODE REVIEW

**Review by zrock-dev — COMMENTED** [review]
> This **PR** sets the required configuration for Swagger documentation besides of implementing the project structure using a Clean Architecture.

Please document what is this PR solving and what are the why's behind the proposed implementation.

> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27#-:-OCu3ZKGC6jGRR-UQXrx:b8or1be)* status: 0 of 72 files reviewed, all discussions resolved (waiting on @gabygabylagaby and @luiggy-mamani-jalafund)

**Comment by teran-joseluis** [comment]
> > This **PR** sets the required configuration for Swagger documentation besides of implementing the project structure using a Clean Architecture.
> 
> Please document what is this PR solving and what are the why's behind the proposed implementation.
> 
> > _[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27#-:-OCu3ZKGC6jGRR-UQXrx:b8or1be)_ status: 0 of 72 files reviewed, all discussions resolved (waiting on @gabygabylagaby and @luiggy-mamani-jalafund)

Just updated it. Can you review it now please?

**Review by zrock-dev — COMMENTED** [review]
I've run the following tests.

## Directory comparison

I collected files from both origin/develop and this PR's branch (chore/cs-61-04/project-structure-configuration-setup) and I found out the following differences:



Analyzing those differences, it seems that this PR is changing the name of some files and that has deleted ArgosApplicationTests.java and FileNotFoundExceptionTests.java

### Executed commands
```
1. recollect files from origin/develop
git ls-tree -r --name-only $upstream | sed 's#.*/##' | sort > develop-files.txt

2. recollect files from feature branch
git ls-tree -r --name-only $feature | sed 's#.*/##' | sort > feature-files.txt

```

### Conclusion

I suggest keeping the name of the files as they were, and bring back deleted files (unless they have a valid reason)

> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27#-:-OCu8Kwf1ooS0TMMEFgW:b-e9yleo)* status: 0 of 72 files reviewed, all discussions resolved (waiting on @gabygabylagaby and @luiggy-mamani-jalafund)

**Comment by teran-joseluis** [comment]
> I've run the following tests.
> 
> ## Directory comparison
> I collected files from both origin/develop and this PR's branch (chore/cs-61-04/project-structure-configuration-setup) and I found out the following differences:
> 
> 
> 
> Analyzing those differences, it seems that this PR is changing the name of some files and that has deleted ArgosApplicationTests.java and FileNotFoundExceptionTests.java
> 
> ### Executed commands
> ```
> 1. recollect files from origin/develop
> git ls-tree -r --name-only $upstream | sed 's#.*/##' | sort > develop-files.txt
> 
> 2. recollect files from feature branch
> git ls-tree -r --name-only $feature | sed 's#.*/##' | sort > feature-files.txt
> ```
> 
> ### Conclusion
> I suggest keeping the name of the files as they were, and bring back deleted files (unless they have a valid reason)
> 
> > _[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27#-:-OCu8Kwf1ooS0TMMEFgW:b-e9yleo)_ status: 0 of 72 files reviewed, all discussions resolved (waiting on @gabygabylagaby and @luiggy-mamani-jalafund)

Yeah, I agree with you but the reason I why have changed theses files or its names on specific it's because they were written on a plural sense instead of being in a singular format. Also, as the most of our unit test files were on singular that's why I decided either to change them to singular.

**Comment by zrock-dev** [comment]
It makes sense. 

Okay, could you update the PR description to reflect this changes too? It would serve for documentation purposes if anyone has doubts on why it has been changed

And, what about the deleted files?

**Comment by teran-joseluis** [comment]
> It makes sense.
> 
> Okay, could you update the PR description to reflect this changes too? It would serve for documentation purposes if anyone has doubts on why it has been changed
> 
> And, what about the deleted files?

PR description has been updated.

And talking about deleted files, probably they should change due to the new directory structure because I only moved them to new folders like the rest but theses ones should be marked as new while I was adding them to the stage area. If you see those files, it happens the same on `src` and `test` directories but except for this file `ArgosApplicationMainTest.java` that was referring to the unit tests of main project class but we already one unit test class for it and I just moved its only one unit test function to the central one and deleted the one duplicated.

**Review by zrock-dev — COMMENTED** [review]
Ok, thank you for updating the documentation.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosAPI/27#-:-OCz6RBg4LVXISQjHvU2:bgf17ve)* status: 0 of 72 files reviewed, all discussions resolved (waiting on @gabygabylagaby and @leonardo-herrera-jalafund)

**Review by zrock-dev — APPROVED** [review]

**Review by GabyGV-GGV — APPROVED** [review]

**Review by leonardo-herrera-jalafund — APPROVED** [review]

**Comment by leonardo-herrera-jalafund** [comment]
Resolve the conflicts

**Comment by teran-joseluis** [comment]
> Resolve the conflicts

It's done.

**Pull request merged**
